spring:
  application:
    name: bookstore-inventory-management-service
  datasource:
    url: jdbc:postgresql://localhost:5432/postgres
    username: postgres
    password: pw
    driver-class-name: org.postgresql.Driver